<h1>object detection using opencv</h1>
                      <h3>this project is created by YOUNESS AABIBI and AMINE FIRDAWSI <h3>

<h4>task 1 : object detection </h4>

In [68]:
import numpy as np
import cv2
import imutils
import time


In [81]:
# read img
img = cv2.imread('phone.webp')
# showing img
cv2.imshow('image', img)
# wait for key to close
cv2.waitKey(0)
# destroy all windows
cv2.destroyAllWindows()

In [82]:
# convert the imh to rgb format because opencv reads img in bgr format
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# convert img to grey scale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)

cv2.imshow('image', gray)
cv2.imshow('image2', img_rgb) 
cv2.waitKey(0)
cv2.destroyAllWindows()
a=np.array(gray)



In [83]:
# def find_marker(image):
# 	# convert the image to grayscale, blur it, and detect edges
# 	gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# 	gray = cv2.GaussianBlur(gray, (5, 5), 0)
# 	edged = cv2.Canny(gray, 35, 125)
# 	# find the contours in the edged image and keep the largest one;
# 	# we'll assume that this is our piece of paper in the image
# 	cnts = cv2.findContours(edged.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
# 	cnts = imutils.grab_contours(cnts)
# 	c = max(cnts, key = cv2.contourArea)
# 	# compute the bounding box of the of the paper region and return it
# 	return cv2.minAreaRect(c)

In [84]:
# img_cascade = cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')
# found = img_cascade.detectMultiScale(gray, minSize =(20, 20))

# if len(found):
#     for (x,y,widht,height) in found:
#         cv2.rectangle(img, (x,y), (x+widht, y+height), (0,255,0), 2)
# cv2.imshow('image', img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [85]:
ret, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
canny = cv2.Canny(img, 100, 200)
cv2.imshow('image', thresh)
cv2.imshow('image2', canny)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [86]:
print(canny)
max_x,min_x,max_y,min_y = [0,10000000,0,10000000]
height,width = canny.shape
print(canny.shape)
for i in range(0, height):             
    for j in range(0, (width)):
        if canny[i,j]==255:
            if j>=max_x:
                max_x=j
            if j<=min_x:
                min_x=j
            if i>=max_y:
                max_y=i
            if i<=min_y:
                min_y=i
print(max_x,max_y,min_x,min_y)
x=min_x
y=min_y
widht = max_x - min_x
height = max_y - min_y
cv2.rectangle(img,(x,y), (x+widht, y+height),(0,255,0),2)      
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()     

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(500, 500)
456 478 43 57


In [30]:
# img_copy2 = img.copy()
# marker = find_marker(img_copy2)
# box = cv2.cv.BoxPoints(marker) if imutils.is_cv2() else cv2.boxPoints(marker)
# box = np.int0(box)
# cv2.drawContours(img_copy2, [box], -1, (0, 255, 0), 2)
# cv2.imshow('image', img_copy2)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [87]:
contours, hierarchy = cv2.findContours(image=canny, mode=cv2.RETR_CCOMP, method=cv2.CHAIN_APPROX_SIMPLE)
img_copy = img.copy()
cv2.drawContours(img_copy, contours, -1, (255,0,0), 1,cv2.LINE_AA)
cv2.imshow('image', img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

<h4>Task2 : face detection </h4>

In [88]:
import cv2
import numpy as np

In [89]:
# read input from web cam
cap = cv2.VideoCapture(0)
#get the cascade classifer object using the haarcascade file
img_cascade = cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_alt.xml')
while True:
    # read frame
    ret, frame = cap.read()
    # flip the frame so that it is not the mirror view
    frame = cv2.flip(frame, 1)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # detecting the face in the frame
    found = img_cascade.detectMultiScale(gray, 1.1,5)
    # draw a rectangle around the face
    if len(found):
        for (x,y,widht,height) in found:
            cv2.rectangle(frame, (x,y), (x+widht, y+height), (0,255,0), 2)
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

<h4>task3 : face and hands detection </h4>

In [90]:
import cv2
import numpy as np


In [91]:
#reading the input webcam
cap = cv2.VideoCapture(0)
# hand_cascade = cv2.CascadeClassifier('./haarcascade/haarcascade_hand.xml')
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_alt.xml')
palm_cascade = cv2.CascadeClassifier('./haarcascade/1256617233-1-haarcascade_hand.xml')
while True :
    ret,frame = cap.read()
    frame = cv2.flip(frame,1)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    min_YCrCb = np.array([0,133,77],np.uint8)
    max_YCrCb = np.array([235,173,127],np.uint8)
    imageYCrCb = cv2.cvtColor(frame,cv2.COLOR_BGR2YCR_CB)
    skinRegionYCrCb = cv2.inRange(imageYCrCb,min_YCrCb,max_YCrCb)
    skinYCrCb = cv2.bitwise_and(frame, frame, mask = skinRegionYCrCb)
    #Erosion
    kernel = np.ones((2,2), np.uint8)

    erode_image = cv2.erode(skinYCrCb,kernel, iterations=1)
    
    cv2.imshow('image', erode_image)
    found_palm = palm_cascade.detectMultiScale(erode_image, 1.1,16)
    found_face = face_cascade.detectMultiScale(frame, 1.1,15)
    
    if len(found_palm):
        for (x,y,widht,height) in found_palm:
            cv2.rectangle(frame, (x,y), (x+widht, y+height), (0,255,0), 2)
    if len(found_face):
        for (x,y,widht,height) in found_face:
            cv2.rectangle(frame, (x,y), (x+widht, y+height), (255,0,0), 2)

    cv2.imshow('frame', frame)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()



task 4

In [92]:
import cv2
import numpy as np

In [94]:
cap = cv2.VideoCapture(0)
hand_cascade = cv2.CascadeClassifier('./haarcascade/1256617233-1-haarcascade_hand.xml')
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_alt.xml')
points = []
blank = np.zeros([512,512,3],dtype=np.uint8)
blank.fill(255)
fx,fy,fw,fh = [0,0,0,0]
while True :
    ret,frame = cap.read()
    frame = cv2.flip(frame,1)
    min_YCrCb = np.array([0,133,77],np.uint8)
    max_YCrCb = np.array([235,173,127],np.uint8)
    imageYCrCb = cv2.cvtColor(frame,cv2.COLOR_BGR2YCR_CB)
    skinRegionYCrCb = cv2.inRange(imageYCrCb,min_YCrCb,max_YCrCb)
    skinYCrCb = cv2.bitwise_and(frame, frame, mask = skinRegionYCrCb)
    #Erosion
    kernel = np.ones((2,2), np.uint8)

    erode_image = cv2.erode(skinYCrCb,kernel, iterations=1)
    found = hand_cascade.detectMultiScale(erode_image, 1.1,15)
    found_face = face_cascade.detectMultiScale(frame, 1.1,5)
    if len(found):
        
        if len(found_face):
            fx,fy,fw,fh = found_face[0]
        for (x,y,widht,height) in found:
            cv2.rectangle(frame, (x,y), (x+widht, y+height), (0,255,0), 2)
            center = (x + widht//2, y + height//2)
            cv2.circle(frame, center, 20, (255, 0, 0), 2)
            if center[0]>= fx and center[0] <= fx+fw and center[1] >= fy and center[1] <= fy+fh:
                points=[] 
            elif len(points) <2:
                points.append(center)
            else:
                for i in range(1,len(points)):
                    cv2.line(blank, points[i-1], points[i], (0, 0, 255), 2)
                points.append(center)
    if len(found_face):
        for (x,y,widht,height) in found_face:
            cv2.rectangle(frame, (x,y), (x+widht, y+height), (255,0,0), 2)
    cv2.imshow('frame', frame)
    cv2.imshow('image', blank)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()